### ISSUE TITLE
案例库的后台界面还没弄好

### ISSUE THREAD

**Issue by Niracler** [UMLTeam/DearHouAimin#141]
**描述错误**  
对bug的清晰简洁描述。  

**重现**  
重现行为的步骤：  
1.去'...'  
2.点击'....'  
3.向下滚动到'....'  
4.看错误  

**预期行为**  
清楚简洁地描述您期望发生的事情。  

**截图**  
如果适用，请添加屏幕截图以帮助解释您的问题。  

**桌面（请填写以下信息）：**    
   - 操作系统:  
   - 浏览器:   
   - 版本:    
  
**智能手机（请填写以下信息）：**  
   - 设备:  
   - 操作系统:  
   - 浏览器:  
   - 版本:  

**附加背景**
在此添加有关此问题的任何其他上下文。

**Comment by Ellenfu** [comment]
fix #141
